name: NyanClans
version: ${project.version}
main: nyanclans.core.NyanClansPlugin
author: NyanGuyMF

description: |-
  The NyanClans plugin is fully customisable Bukkit plugin
  with database storage for clans and players.

softdepend: [Vault, ProtocolLib]

load: POSTWORLD
